### ISSUE TITLE
Bridge between interaction & message

### ISSUE THREAD

**Issue by KurokuTetsuya** [KurokuTetsuya/gorou#21]
Making command with 2 different functions which interaction and command aren't efficient. As @Hazmi35 said, looks like I have to create a bridge between interaction and commands like `CommandContext`. This will be breaking changes to this project because I have to rewrite the command structures

**Comment by KurokuTetsuya** [comment]
@Hazmi35 wdyt? 
![bridge](https://user-images.githubusercontent.com/45705890/130310374-c70209b2-c554-4c57-a1f5-205e190cfb57.png)

**Comment by KurokuTetsuya** [comment]
The additional parameter `reply` or `editReply` purpose is for indicating what should interaction do

**Comment by Hazmi35** [comment]
> @Hazmi35 wdyt?
> ![bridge](https://user-images.githubusercontent.com/45705890/130310374-c70209b2-c554-4c57-a1f5-205e190cfb57.png)

That's what I've been talking about this entire time. Just didn't have time to implement it
